TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../../rtl/sign_extender.sv
TOPLEVEL = sign_extender
MODULE = sign_extender_tb
SIM = icarus
COMPILE_ARGS = -g2012
WAVES = 1
include $(shell cocotb-config --makefiles)/Makefile.sim
