TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../../rtl/alu_decoder.sv
TOPLEVEL = alu_decoder
MODULE = alu_decoder_tb
SIM = icarus
COMPILE_ARGS = -g2012
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim
