TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../../rtl/alu.sv
TOPLEVEL = alu
MODULE = alu_tb
SIM = icarus
COMPILE_ARGS = -g2012
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim                                             