TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../rtl/Program_counter.sv
TOPLEVEL = Program_counter
MODULE = pc_tb
SIM = icarus
COMPILE_ARGS = -g2012
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim
