TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/../../rtl/Register_file.sv
TOPLEVEL = Register_file
MODULE = Register_file_tb
SIM = icarus
COMPILE_ARGS = -g2012
WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim
